import Config

# Configure your database
config :obelisk, Obelisk.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "obelisk_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :obelisk, ObeliskWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "BsYEnM9vKlcaP7f5HqhVBExSZIU1uCYv1ItiL0t/+Azi5/4GeKTfsfo/VA6KsRVC",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:obelisk, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:obelisk, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :obelisk, ObeliskWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/obelisk_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :obelisk, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Development-specific Obelisk settings
config :obelisk,
  # Enable more verbose logging in development
  log_level: :debug,
  # Disable async processing in dev for easier debugging
  async_embedding: false,
  # Smaller batch sizes for faster feedback
  embedding_batch_size: 5

# LLM Provider development settings
# These can be overridden with environment variables

# OpenAI settings (default provider)
config :obelisk, :openai,
  # Will be read from OPENAI_API_KEY environment variable
  api_key: {:system, "OPENAI_API_KEY"},
  # Default model for development (cheaper)
  model: System.get_env("OPENAI_MODEL", "gpt-4o-mini"),
  base_url: "https://api.openai.com/v1"

# Anthropic settings
config :obelisk, :anthropic,
  # Will be read from ANTHROPIC_API_KEY environment variable  
  api_key: {:system, "ANTHROPIC_API_KEY"},
  model: System.get_env("ANTHROPIC_MODEL", "claude-3-5-sonnet-20241022"),
  base_url: "https://api.anthropic.com/v1"

# Ollama settings (for local development)
config :obelisk, :ollama,
  base_url: System.get_env("OLLAMA_BASE_URL", "http://localhost:11434"),
  model: System.get_env("OLLAMA_MODEL", "llama3.2"),
  # Timeout for local models (they can be slower)
  timeout: 60_000

# Embedding service settings
config :obelisk, :embeddings,
  provider: "openai",
  model: "text-embedding-3-small",
  # Smaller dimensions for development
  dimensions: 1536
